wandb_version: 1

image_size:
  desc: null
  value: 256
batch_size:
  desc: null
  value: 16
grad_accumulation_steps:
  desc: null
  value: 2
num_epochs:
  desc: null
  value: 1
start_model:
  desc: null
  value: google/ddpm-bedroom-256
dataset_name:
  desc: null
  value: huggan/wikiart
device:
  desc: null
  value: cuda
model_save_name:
  desc: null
  value: sajjad_1e
wandb_project:
  desc: null
  value: dm_finetune
log_samples_every:
  desc: null
  value: 250
save_model_every:
  desc: null
  value: 2500
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712507584.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      - 105
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.6
      6: 4.30.2
      8:
      - 5
      - 15
      13: linux-x86_64
